In [1]:
import pandas as pd
import numpy as np

# Molecules Data Frame

In [2]:
def df_sdf_files (direction_file):
    
    """
    This funtion associate the BindingDB_Reactant_set_id with the NAME, 
    Target Source Organism According to Curator or DataSource and IC50 (nM) value
    of .sdf files the Binding Database
    """
    
    with open (direction_file, "r", encoding = "utf-8") as f:
        molecules3D_1 = f.readlines()

    BindingDB_Reactant_set_id = [line.strip("\n") for idx, line in enumerate(molecules3D_1) if (molecules3D_1[idx-1]).startswith("> <BindingDB Reactant_set_id>")]
    Name = [line.strip("\n") for idx, line in enumerate(molecules3D_1) if (molecules3D_1[idx-1]).startswith("$$$$")]
    IC50_nM = [line.strip("\n") for idx, line in enumerate(molecules3D_1) if (molecules3D_1[idx-1]).startswith("> <IC50")]
    Target_Source_Organism = [line.strip("\n") for idx, line in enumerate(molecules3D_1) if (molecules3D_1[idx-1]).startswith("> <Target Source Organism According to Curator or DataSource>")]
    Dict = []

    for i in range (len(BindingDB_Reactant_set_id)):
            Dict.append({"BindingDB_Reactant_set_id": BindingDB_Reactant_set_id[i],
                         "Name": Name[i],
                         "Target Source Organism According to Curator or DataSource": Target_Source_Organism[i],
                         "IC50 (nM)": IC50_nM[i]
                        })
    df_molecules = pd.DataFrame(Dict)        

    return df_molecules

Data_Frame = df_sdf_files ("../ACETYLCHOLINESTERASE_3D_Dataframe.sdf") 

Data_Frame

,BindingDB_Reactant_set_id,Name,Target Source Organism According to Curator or DataSource,IC50 (nM)
0,51056129,tacrine,Electrophorus electricus,110
1,51056130,BindingDB_50430725_mol_1,Electrophorus electricus,456
2,51056131,BindingDB_50430726_mol_1,Electrophorus electricus,55
3,51056132,BindingDB_50430727_mol_1,Electrophorus electricus,79
4,51056133,BindingDB_50430728_mol_1,Electrophorus electricus,82
...,...,...,...,...
10025,51297250,,Electrophorus electricus,943
10026,51297258,,Electrophorus electricus,559
10027,51283328,,Electrophorus electricus,
10028,51288963,,Electrophorus electricus,206
10029,51292556,BindingDB_4078_mol_1,Electrophorus electricus,132920

# # Import molecular descriptors  2D Alvades PCC 0.95 and filter matrix

In [3]:
    descriptors = pd.read_csv("../Descriptors/output_alvadescriptorsPCC0.95.txt", sep = "\t", index_col = 0)

df_2Ddescriptors_Alv_PCC095 = descriptors[5:10035]
df_2Ddescriptors_Alv_PCC095.index = [i for i in range (10030)]

df_2Ddescriptors_Alv_PCC095 = pd.merge(Data_Frame["BindingDB_Reactant_set_id"], df_2Ddescriptors_Alv_PCC095.drop(["NAME"],axis = 1), left_index = True, right_index = True)

df_2Ddescriptors_Alv_PCC095

,BindingDB_Reactant_set_id,MW,AMW,Me,Mp,Mi,GD,nTA,nBM,RBN,...,s2_numRotBonds,s3_numRotBonds,s4_numRotBonds,s1_numAroBonds,s2_numAroBonds,s3_numAroBonds,s4_numAroBonds,s34_size,s34_phSize,s34_phRelSize
0,51056129,198.29,6.8376,0.9829,0.6752,1.1203,0.1619,1,11,0,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000
1,51056130,483.76,6.2826,0.9795,0.6485,1.1246,0.0619,3,18,13,...,0.0,2.0000,9.0,0.0,0.0,6.0,11.0,34.0,4.0,0.1111
2,51056131,546.26,6.5814,0.9821,0.6544,1.1249,0.0567,4,18,15,...,0.0,1.0000,12.0,0.0,0.0,0.0,17.0,37.0,4.0,0.1026
3,51056132,518.20,6.7299,0.9837,0.6597,1.1239,0.0601,4,18,13,...,0.0,1.0000,10.0,0.0,0.0,0.0,17.0,35.0,4.0,0.1081
4,51056133,504.17,6.8131,0.9846,0.6626,1.1233,0.0619,4,18,12,...,0.0,1.0000,9.0,0.0,0.0,0.0,17.0,34.0,4.0,0.1111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10025,51297250,350.51,6.7406,0.9895,0.6510,1.1302,0.0892,3,16,4,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000
10026,51297258,356.84,8.4962,1.0136,0.6933,1.1253,0.0933,3,17,2,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000
10027,51283328,591.08,7.6764,0.9963,0.6722,1.1300,0.0553,3,22,11,...,0.0,1.0000,8.0,0.0,0.0,10.0,11.0,35.0,5.0,0.1282
10028,51288963,401.62,6.8071,0.9901,0.6515,1.1233,0.0794,5,14,7,...,0.0,0.6667,6.0,0.0,0.0,0.0,12.0,24.5,4.0,0.1429
10029,51292556,302.20,10.7929,1.0810,0.7114,1.1043,0.1082,6,14,0,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000

# Filtring by Funtionality Values of Biological Activity and Target Source Organism . DISTRIBUTION AND SOME STATISTICS ABOUT pIC50 VALUE

In [4]:
def filter_VBA_BO (Data_Frame, Target_Source_Organism):
    """
    This funtion filter Data Frame by Funtionality of 
    biological activity values to calculate pIC50 and
    to interpretate the results of the model, also
    filter by Target Source Organism in str format, It
    return a Data Frame ready to add the molecular
    descriptors and calcualte the prediction model and
    some statistics parameters
    """
    
    Molecules_IC50 = []

    for i in range(len(Data_Frame)):

        if  Data_Frame.loc[i,"Target Source Organism According to Curator or DataSource"] == Target_Source_Organism and not Data_Frame.loc[i,"IC50 (nM)"] == "" and not ">" in Data_Frame.loc[i,"IC50 (nM)"] and not "<" in Data_Frame.loc[i,"IC50 (nM)"]:

            Molecules_IC50.append ({"BindingDB_Reactant_set_id": Data_Frame.loc[i,"BindingDB_Reactant_set_id"],
                                    "Name": Data_Frame.loc[i, "Name"],
                                    "IC50 (nM)": float(Data_Frame.loc[i,"IC50 (nM)"]),
                                    "pIC50": -np.log10((float(Data_Frame.loc[i,"IC50 (nM)"])*10**(-9)))
                                    })


    df_Molecules_IC50 = pd.DataFrame(Molecules_IC50)
    
    return df_Molecules_IC50, df_Molecules_IC50["pIC50"].describe()


Target_Source_Organism = "Electrophorus electricus" 

df_filter, statistics = filter_VBA_BO (Data_Frame, Target_Source_Organism) 

print(statistics)

df_filter

count    5566.000000
mean        5.887610
std         1.312085
min         0.618000
25%         4.897995
50%         5.785156
75%         6.853872
max        14.262807
Name: pIC50, dtype: float64

     BindingDB_Reactant_set_id                      Name  IC50 (nM)     pIC50
0                     51056129                   tacrine      110.0  6.958607
1                     51056130  BindingDB_50430725_mol_1      456.0  6.341035
2                     51056131  BindingDB_50430726_mol_1       55.0  7.259637
3                     51056132  BindingDB_50430727_mol_1       79.0  7.102373
4                     51056133  BindingDB_50430728_mol_1       82.0  7.086186
...                        ...                       ...        ...       ...
5561                  51297249                                616.0  6.210419
5562                  51297250                                943.0  6.025488
5563                  51297258                                559.0  6.252588
5564                  51288963                                206.0  6.686133
5565                  51292556      BindingDB_4078_mol_1   132920.0  3.876410

[5566 rows x 4 columns]

# Filtring Data Frame Molecular Descriptors 2D by the DataFrame Filter

In [10]:
Lista_idx = []
Ddescriptors_Alv_PCC095_filter = []

for idx, value in enumerate(df_2Ddescriptors_Alv_PCC095.iloc[:,0]):
    if value in list(df_filter.iloc[:,0]):
        Lista_idx.append(idx)
        Ddescriptors_Alv_PCC095_filter.append(df_2Ddescriptors_Alv_PCC095.iloc[idx,:]) 
    
df_2Ddescriptors_Alv_PCC095_filter = pd.DataFrame(Ddescriptors_Alv_PCC095_filter)
df_2Ddescriptors_Alv_PCC095_filter.index = [i for i in range(len(df_filter))]

df_2Ddescriptors_Alv_PCC095_filter

,BindingDB_Reactant_set_id,MW,AMW,Me,Mp,Mi,GD,nTA,nBM,RBN,...,s2_numRotBonds,s3_numRotBonds,s4_numRotBonds,s1_numAroBonds,s2_numAroBonds,s3_numAroBonds,s4_numAroBonds,s34_size,s34_phSize,s34_phRelSize
0,51056129,198.29,6.8376,0.9829,0.6752,1.1203,0.1619,1,11,0,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000
1,51056130,483.76,6.2826,0.9795,0.6485,1.1246,0.0619,3,18,13,...,0.0,2.0000,9.0,0.0,0.0,6.0,11.0,34.0,4.0,0.1111
2,51056131,546.26,6.5814,0.9821,0.6544,1.1249,0.0567,4,18,15,...,0.0,1.0000,12.0,0.0,0.0,0.0,17.0,37.0,4.0,0.1026
3,51056132,518.20,6.7299,0.9837,0.6597,1.1239,0.0601,4,18,13,...,0.0,1.0000,10.0,0.0,0.0,0.0,17.0,35.0,4.0,0.1081
4,51056133,504.17,6.8131,0.9846,0.6626,1.1233,0.0619,4,18,12,...,0.0,1.0000,9.0,0.0,0.0,0.0,17.0,34.0,4.0,0.1111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5561,51297249,366.41,8.1424,1.0200,0.6705,1.1275,0.0883,2,17,2,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000
5562,51297250,350.51,6.7406,0.9895,0.6510,1.1302,0.0892,3,16,4,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000
5563,51297258,356.84,8.4962,1.0136,0.6933,1.1253,0.0933,3,17,2,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000
5564,51288963,401.62,6.8071,0.9901,0.6515,1.1233,0.0794,5,14,7,...,0.0,0.6667,6.0,0.0,0.0,0.0,12.0,24.5,4.0,0.1429
5565,51292556,302.20,10.7929,1.0810,0.7114,1.1043,0.1082,6,14,0,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000

# Data Frame to construc the models 2D

In [13]:
df_2ML = pd.merge(df_filter, df_2Ddescriptors_Alv_PCC095_filter.drop("BindingDB_Reactant_set_id", axis = 1), left_index = True, right_index = True)

df_2ML

,BindingDB_Reactant_set_id,Name,IC50 (nM),pIC50,MW,AMW,Me,Mp,Mi,GD,...,s2_numRotBonds,s3_numRotBonds,s4_numRotBonds,s1_numAroBonds,s2_numAroBonds,s3_numAroBonds,s4_numAroBonds,s34_size,s34_phSize,s34_phRelSize
0,51056129,tacrine,110.0,6.958607,198.29,6.8376,0.9829,0.6752,1.1203,0.1619,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000
1,51056130,BindingDB_50430725_mol_1,456.0,6.341035,483.76,6.2826,0.9795,0.6485,1.1246,0.0619,...,0.0,2.0000,9.0,0.0,0.0,6.0,11.0,34.0,4.0,0.1111
2,51056131,BindingDB_50430726_mol_1,55.0,7.259637,546.26,6.5814,0.9821,0.6544,1.1249,0.0567,...,0.0,1.0000,12.0,0.0,0.0,0.0,17.0,37.0,4.0,0.1026
3,51056132,BindingDB_50430727_mol_1,79.0,7.102373,518.20,6.7299,0.9837,0.6597,1.1239,0.0601,...,0.0,1.0000,10.0,0.0,0.0,0.0,17.0,35.0,4.0,0.1081
4,51056133,BindingDB_50430728_mol_1,82.0,7.086186,504.17,6.8131,0.9846,0.6626,1.1233,0.0619,...,0.0,1.0000,9.0,0.0,0.0,0.0,17.0,34.0,4.0,0.1111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5561,51297249,,616.0,6.210419,366.41,8.1424,1.0200,0.6705,1.1275,0.0883,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000
5562,51297250,,943.0,6.025488,350.51,6.7406,0.9895,0.6510,1.1302,0.0892,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000
5563,51297258,,559.0,6.252588,356.84,8.4962,1.0136,0.6933,1.1253,0.0933,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000
5564,51288963,,206.0,6.686133,401.62,6.8071,0.9901,0.6515,1.1233,0.0794,...,0.0,0.6667,6.0,0.0,0.0,0.0,12.0,24.5,4.0,0.1429
5565,51292556,BindingDB_4078_mol_1,132920.0,3.876410,302.20,10.7929,1.0810,0.7114,1.1043,0.1082,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000

# Save File Input_Docking

In [ ]:
with open ("../ACETYLCHOLINESTERASE_3D.sdf", "r", encoding = "utf-8") as f:
        molecules3D_1 = f.readlines()


idx = 0
docking_rever = []

for i in df_filter.iloc[:,0]:
    idx = molecules3D_1.index(str(i) + "\n") -5
        
    while molecules3D_1[idx] != "$$$$\n":
        docking_rever. append (molecules3D_1[idx])
        idx -= 1
    
    docking_rever. append (molecules3D_1[idx])


docking = docking_rever[::-1]


with open("./input_molecules_docking.sdf", "w", encoding = "utf-8") as a:
    for x in docking:
        Docking = a.writelines(x)